import os
import tempfile


# ----------------------------------------------------------------------
# Serial ports are detected through /dev/ symlinks created by udev.
# The rules live in UDEV_RULES_PATH and are installed by
# installUdevRules() at startup (idempotent — only re-installs when the
# rules text actually changes).
#
# Possible combinations of attached devices:
#   - none
#   - coin acceptor only (v6 OR v7)
#   - card terminal + coin acceptor (v6 OR v7)
#   - card terminal alone
# ----------------------------------------------------------------------

# Symlink paths created by the udev rules
CARD_TERMINAL_SYMLINK    = "/dev/card_terminal"
COIN_ACCEPTOR_V6_SYMLINK = "/dev/coin_accept_v6"
COIN_ACCEPTOR_V7_SYMLINK = "/dev/coin_accept_v7"

# Where the udev rules file should live on disk
UDEV_RULES_PATH = "/etc/udev/rules.d/99-groenborg-serial.rules"

# Module-level state (kept for backwards compatibility with comforttan.py)
CoinAcceptorPort     = "none"
CardReaderPort       = "none"
# 'none', 'v6' (existing EMP protocol) or 'v7' (new EMP protocol)
CoinAcceptorProtocol = "none"


# ----------------------------------------------------------------------
# udev rule installation
# ----------------------------------------------------------------------

def buildUdevRulesText(rule_list, header=True):
    """Render a list of rule dicts into a rules-file string.

    Each rule is a dict with keys:
        vid     - USB idVendor  (lowercase hex string, e.g. '0403')
        pid     - USB idProduct (lowercase hex string, e.g. '6015')
        symlink - name to expose under /dev/ (e.g. 'card_terminal')
        mode    - (optional) file mode, default '0666'
        comment - (optional) line comment placed above the rule
    """
    lines = []
    if header:
        lines.append("# /etc/udev/rules.d/99-groenborg-serial.rules")
        lines.append("# Auto-generated by HW_IO.installUdevRules() — do not edit by hand.")
        lines.append("# Identify a device's IDs with:")
        lines.append("#   lsusb -v | grep -E \"iSerial|iProduct|idVendor|idProduct\"")
        lines.append("")
    for r in rule_list:
        if r.get("comment"):
            lines.append("# " + r["comment"])
        mode = r.get("mode", "0666")
        lines.append(
            'SUBSYSTEM=="tty", '
            'ATTRS{{idVendor}}=="{vid}", '
            'ATTRS{{idProduct}}=="{pid}", '
            'SYMLINK+="{sym}", '
            'MODE="{mode}"'.format(
                vid=r["vid"], pid=r["pid"], sym=r["symlink"], mode=mode
            )
        )
    return "\n".join(lines) + "\n"


def _readFileSafely(path):
    try:
        with open(path, "r") as f:
            return f.read()
    except Exception:
        return None


def installUdevRules(rules, reload_on_change=True):
    """Install udev rules under UDEV_RULES_PATH, idempotently.

    `rules` may be either:
        - a string (the full file content), or
        - a list of rule dicts (see buildUdevRulesText).

    Returns True if the file was updated and udev was reloaded,
    False if no change was needed (or the install failed).
    """
    if isinstance(rules, (list, tuple)):
        desired = buildUdevRulesText(rules)
    else:
        desired = rules if rules.endswith("\n") else rules + "\n"

    current = _readFileSafely(UDEV_RULES_PATH)
    if current == desired:
        print("udev rules already up to date at " + UDEV_RULES_PATH)
        return False

    # We can't write to /etc/udev/rules.d/ without root, so stage the
    # file in /tmp and sudo-copy it into place.
    tmp = tempfile.NamedTemporaryFile(
        mode="w", delete=False, suffix=".rules", prefix="groenborg-udev-"
    )
    try:
        tmp.write(desired)
        tmp.flush()
        tmp.close()

        rc = os.system("sudo cp '{0}' '{1}'".format(tmp.name, UDEV_RULES_PATH))
        if rc != 0:
            print("Failed to install udev rules: sudo cp returned {0}".format(rc))
            return False
        os.system("sudo chmod 644 '{0}'".format(UDEV_RULES_PATH))
        os.system("sudo chown root:root '{0}'".format(UDEV_RULES_PATH))
    finally:
        try:
            os.unlink(tmp.name)
        except Exception:
            pass

    print("Installed udev rules to " + UDEV_RULES_PATH)

    if reload_on_change:
        os.system("sudo udevadm control --reload-rules")
        os.system("sudo udevadm trigger --subsystem-match=tty")
        print("Reloaded udev rules")

    return True


# ----------------------------------------------------------------------
# Port detection
# ----------------------------------------------------------------------

def _exists(path):
    """Return True if a /dev/ symlink (or device) is currently present.

    os.path.exists follows symlinks, so a dangling symlink (device
    unplugged) correctly returns False.
    """
    return os.path.exists(path)


def getCardReaderPort():
    """Detect the card terminal via the 'card_terminal' udev symlink."""
    global CardReaderPort
    if _exists(CARD_TERMINAL_SYMLINK):
        CardReaderPort = CARD_TERMINAL_SYMLINK
    else:
        CardReaderPort = "none"
    print('CardReaderPort: ' + CardReaderPort)
    return CardReaderPort


def getCoinAcceptorPort():
    """Detect the coin acceptor and which serial protocol to use.

    v6 takes precedence over v7 if (for some reason) both are present,
    matching the historical behaviour of the existing installation.
    Also sets `CoinAcceptorProtocol` to 'v6', 'v7' or 'none'.
    """
    global CoinAcceptorPort
    global CoinAcceptorProtocol

    if _exists(COIN_ACCEPTOR_V6_SYMLINK):
        CoinAcceptorPort     = COIN_ACCEPTOR_V6_SYMLINK
        CoinAcceptorProtocol = "v6"
    elif _exists(COIN_ACCEPTOR_V7_SYMLINK):
        CoinAcceptorPort     = COIN_ACCEPTOR_V7_SYMLINK
        CoinAcceptorProtocol = "v7"
    else:
        CoinAcceptorPort     = "none"
        CoinAcceptorProtocol = "none"

    print('CoinAcceptorPort: '     + CoinAcceptorPort)
    print('CoinAcceptorProtocol: ' + CoinAcceptorProtocol)

    # Belt-and-braces: the udev rule already sets MODE="0666", but if
    # the rule was just installed and udev hasn't re-tagged the node
    # yet, force the permissions now.
    if CoinAcceptorPort != "none":
        os.system("sudo chmod 777 " + CoinAcceptorPort)

    return CoinAcceptorPort


def getCoinAcceptorProtocol():
    """Return 'none', 'v6' or 'v7'.

    Call AFTER getCoinAcceptorPort() so the value is up to date.
    """
    return CoinAcceptorProtocol
